name: frontend

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    # environment:
    #   VITE_API_BASE_URL: ${VITE_API_URL}
    #   VITE_NODE_ENV: ${VITE_NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
